name: identity
description: A new Flutter application.
version: 0.2.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  identity_mobile:
    path: ./plugins/identity_mobile
  cupertino_icons: ^0.1.2
  faker: ^1.2.1
  base58check: ^1.0.1
  # web_socket_channel: ^1.1.0
  json_annotation: ^3.0.0
  intl: ^0.16.1
  # menu:
  #   git:
  #     url: https://github.com/geoah/flutter_long_tap_menu.git
  flutter_linkify: ^3.1.0
  url_launcher: ^5.4.2
  # adhara_markdown:
  #   git:
  #     url: https://github.com/geoah/flutter_markdown.git
  #     ref: 1d7ca31
  # file_picker: ^1.5.0+2
  google_fonts: ^0.3.10
  flutter_secure_storage: ^3.3.3
  timeago: ^2.0.26
  # badges: ^1.1.1
  local_auth_device_credentials: ^0.6.3+8
  settings_ui: ^0.3.0
  qr_flutter: ^3.1.0
  flutter_icons: ^1.1.0
  barcode_scan: ^3.0.1
  focus_detector: ^1.0.2
  progress_state_button: ^1.0.1
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.3

flutter:
  uses-material-design: true
  assets:
   - images/nimona-white.png
   - images/nimona-blue.png
