// Objective-C API for talking to mochi.io/mobile Go package.
//   gobind -lang=objc mochi.io/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobileapi_H__
#define __Mobileapi_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileapiDataProcessor;
@class MobileapiIdentity;

/**
 * DataProcessor :
 */
@interface MobileapiDataProcessor : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Increment : Increment the int received as an argument.
 */
- (BOOL)increment:(long)data ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
@end

@interface MobileapiIdentity : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull privateKey;
@property (nonatomic) NSString* _Nonnull privateKeyMnemonic;
@property (nonatomic) NSString* _Nonnull publicKey;
@property (nonatomic) NSString* _Nonnull name;
@end

FOUNDATION_EXPORT MobileapiIdentity* _Nullable MobileapiCreateNewIdentity(NSString* _Nullable name);

FOUNDATION_EXPORT NSString* _Nonnull MobileapiCreateNewIdentityString(void);

FOUNDATION_EXPORT NSString* _Nonnull MobileapiStartDaemon(void);

#endif
