
// Objective-C API for talking to the following Go packages
//
//	mochi.io/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mobileapi_FRAMEWORK_H__
#define __Mobileapi_FRAMEWORK_H__

#include "Mobileapi.objc.h"
#include "Universe.objc.h"

#endif
