default_platform(:ios)
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci
    sync_code_signing(  
      type: "appstore",
      readonly: is_ci
    )
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
    )
    upload_to_testflight
  end
end