default_platform(:ios)
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci
    sync_code_signing(  
      type: "appstore",
      readonly: is_ci
    )
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
    )
    app_store_connect_api_key(
      key_id: ENV["APPSTORE_CONNECT_KEYID"],
      issuer_id: ENV["APPSTORE_CONNECT_ISSUERID"],
      key_content: ENV["APPSTORE_CONNECT_PRIVATE_KEY"]
    )
    upload_to_testflight
  end
end